# Generated by Django 6.0 on 2025-12-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_sample_author_director_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='sample_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='club_samples/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='sample_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='club_samples/'),
        ),
    ]
