# Generated by Django 6.0 on 2025-12-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_sample_image_1_alter_club_sample_image_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='body',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clubs.club'),
        ),
    ]
